future4code/Moreira-labe-food2

src/routes/Router.js
=> Developer atauan

src/routes/Router.js
=> Edição das Rotas2

src/page/ResultPage/ResultPage.js, src/page/ResultPage/styled.js
=> Tela de Detalhes do Restaurante-1

src/api.js, src/hooks/useForm.js, src/page/AdressPage/AdressPage.js, src/page/AdressPage/styled.js, src/page/SignUpPage/SignUp.js
=> page cadastro de endereço e perfil

src/global/GlobalState.js, src/global/GlobalStateContext.js, src/page/FeedPage/FeedPage.js, src/page/FeedPage/styled.js
=> feddRestaurants

src/page/SearchPage/SearchPage.js, src/page/SearchPage/styled.js
=> estilização searchPage

src/page/CartPage/CartPage.js, src/page/CartPage/styled.js
=> Estilizações: Página Carrinho / Página Busca

src/components/Footer/index.js, src/components/Footer/styled.js, src/page/FeedPage/FeedPage.js, src/page/FeedPage/styled.js, src/page/ResultPage/ResultPage.js, src/page/ResultPage/styled.js, src/page/SearchPage/SearchPage.js, src/page/SearchPage/styled.js
=> add functions project

src/page/CartPage/CartPage.js, src/page/CartPage/styled.js
=> Developer jaime

src/page/EditProfilePage/EditProfilePage.js, src/page/EditProfilePage/styled.js
=> edição de cadastro

src/api.js, src/global/GlobalState.js, src/page/EditAddressPage/EditAddressPage.js, src/page/EditAddressPage/styled.js, src/page/EditProfilePage/EditProfilePage.js, src/page/EditProfilePage/styled.js, src/page/ProfilePage/ProfilePage.js, src/page/ProfilePage/styled.js
=> paginas do perfil e editar

src/components/Footer/index.js, src/page/AdressPage/AdressPage.js, src/page/SignUpPage/SignUp.js
=> atualizações

src/page/SearchPage/SearchPage.js, src/page/SearchPage/styled.js
=> pagina de busca

src/api.js, src/components/Footer/index.js, src/global/GlobalState.js, src/page/CartPage/CartPage.js, src/page/SearchPage/SearchPage.js, src/page/SearchPage/styled.js, src/routes/Router.js, src/routes/coordinator.js
=> atualização carrinho incompleto

src/components/CardProduct/index.js, src/components/CardProduct/styled.js, src/constants/colors.js, src/global/GlobalState.js, src/page/ResultPage/ResultPage.js, src/page/ResultPage/styled.js, src/page/SignUpPage/SignUp.js
=> Carlos henrique developer

src/page/CartPage/CartPage.js, src/routes/Router.js
=> pagina add ao carrinho

src/page/SplashScreen/styled.js
=> splash screen styled

src/components/Footer/index.js, src/page/CartPage/CartPage.js, src/routes/coordinator.js
=> finalizando pagina carrinho

src/api.js, src/page/EditAddressPage/EditAddressPage.js, src/page/EditProfilePage/EditProfilePage.js
=> editar endereço completo e funcionando

src/components/teste/CardRestaurant.js, src/components/teste/styled.js, src/global/GlobalState.js, src/page/CartPage/CartPage.js, src/page/CartPage/styled.js, src/page/ProfilePage/ProfilePage.js, src/page/ProfilePage/styled.js
=> atualização em carrinho
